.PHONY: install
install:
	@mkdir /usr/include/cleri
	@cp ../inc/cleri/*.h /usr/include/cleri/
	@cp libcleri.so /usr/lib/x86_64-linux-gnu/libcleri.so

.PHONY: uninstall
uninstall:
	@rm -f /usr/include/cleri/*.h
	@rmdir /usr/include/cleri/
	@rm -f /usr/lib/x86_64-linux-gnu/libcleri.so

